// <auto-generated />
namespace Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddeddataconstrantstoResume : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddeddataconstrantstoResume));
        
        string IMigrationMetadata.Id
        {
            get { return "201810131813190_Added data constrants to Resume"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
