// <auto-generated />
namespace Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedvalidationconstraintstoLanguageandethnicity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedvalidationconstraintstoLanguageandethnicity));
        
        string IMigrationMetadata.Id
        {
            get { return "201810132329474_added validation constraints to Language and ethnicity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
