// <auto-generated />
namespace Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addingimagepropertiestoskillstables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingimagepropertiestoskillstables));
        
        string IMigrationMetadata.Id
        {
            get { return "201810132104577_Adding image properties to skills tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
